package pl.galajus.brokenpediabackend.admin.common.model;

public enum AdminPsychoEffect {
    CRIT_CHANCE,
    DOUBLE_HIT_CHANCE,

    CRIT_RESISTANCE,
    CRIT_DAMAGE_REDUCTION,

    MAGICAL_DAMAGE_INCREASE,
    PHYSICAL_DAMAGE_INCREASE,

    EXTRA_AP,
    MANA_DRAIN,
    CHANCE_OF_DISENCHANTMENT,

    MAGICAL_HIT_MODIFIER,
    RANGE_HIT_MODIFIER,
    PHYSICAL_HIT_MODIFIER,

    MAGICAL_DEFENCE_MODIFIER,
    RANGE_DEFENCE_MODIFIER,
    PHYSICAL_DEFENCE_MODIFIER,

    EXTRA_FIRE_DAMAGE,
    EXTRA_COLD_DAMAGE,
    EXTRA_ENERGY_DAMAGE,

    RESISTANCE_TO_ROOT,
    RESISTANCE_TO_FREEZING,

    MANA_REGENERATION,
    STAMINA_REGENERATION,
    MANA_USAGE,
    STAMINA_USAGE,

    FARID,
    HOLM,

    MENTAL_ATTACKS_PENETRATION,

    DOUBLE_ATTACK_ROLL_CHANCE,
    DOUBLE_DEFENCE_ROLL_CHANCE,

    PASSIVE_DAMAGE_REDUCTION,
    DAMAGE_REDUCTION,

    CHEAT_DESTINY

}
