--liquibase formatted sql
--changeset galajus:12
create table skill_psycho_effect
(
    id             bigint not null auto_increment PRIMARY KEY,
    skill_basic_id bigint not null,
    psycho_effect  varchar(60),
    value          int    not null,
    constraint fk_skill_psycho_effect_skill_basic_id foreign key (skill_basic_id) references skill_basic (id)
);
--changeset galajus:13
create table skill_custom_effect
(
    id             bigint not null auto_increment PRIMARY KEY,
    skill_basic_id bigint not null,
    description    varchar(100),
    value          int    not null,
    constraint fk_skill_custom_effect_skill_basic_id foreign key (skill_basic_id) references skill_basic (id)
);
--changeset galajus:14
insert into skill_psycho_effect (skill_basic_id, psycho_effect, value) VALUES
(22, 'MAGICAL_HIT_MODIFIER', -9),
(22, 'RANGE_HIT_MODIFIER', -9),
(22, 'PHYSICAL_HIT_MODIFIER', -9),
(23, 'MAGICAL_HIT_MODIFIER', -10),
(23, 'RANGE_HIT_MODIFIER', -10),
(23, 'PHYSICAL_HIT_MODIFIER', -10),
(24, 'MAGICAL_HIT_MODIFIER', -11),
(24, 'RANGE_HIT_MODIFIER', -11),
(24, 'PHYSICAL_HIT_MODIFIER', -11),
(25, 'MAGICAL_HIT_MODIFIER', -12),
(25, 'RANGE_HIT_MODIFIER', -12),
(25, 'PHYSICAL_HIT_MODIFIER', -12),
(26, 'MAGICAL_HIT_MODIFIER', -13),
(26, 'RANGE_HIT_MODIFIER', -13),
(26, 'PHYSICAL_HIT_MODIFIER', -13),
(27, 'MAGICAL_HIT_MODIFIER', -14),
(27, 'RANGE_HIT_MODIFIER', -14),
(27, 'PHYSICAL_HIT_MODIFIER', -14),
(28, 'MAGICAL_HIT_MODIFIER', -15),
(28, 'RANGE_HIT_MODIFIER', -15),
(28, 'PHYSICAL_HIT_MODIFIER', -15),
(29, 'MAGICAL_HIT_MODIFIER', -16),
(29, 'RANGE_HIT_MODIFIER', -16),
(29, 'PHYSICAL_HIT_MODIFIER', -16),
(30, 'MAGICAL_HIT_MODIFIER', -17),
(30, 'RANGE_HIT_MODIFIER', -17),
(30, 'PHYSICAL_HIT_MODIFIER', -17),
(31, 'MAGICAL_HIT_MODIFIER', -18),
(31, 'RANGE_HIT_MODIFIER', -18),
(31, 'PHYSICAL_HIT_MODIFIER', -18),
(32, 'MAGICAL_HIT_MODIFIER', -19),
(32, 'RANGE_HIT_MODIFIER', -19),
(32, 'PHYSICAL_HIT_MODIFIER', -19),
(33, 'MAGICAL_HIT_MODIFIER', -20),
(33, 'RANGE_HIT_MODIFIER', -20),
(33, 'PHYSICAL_HIT_MODIFIER', -20),
(34, 'MAGICAL_HIT_MODIFIER', -21),
(34, 'RANGE_HIT_MODIFIER', -21),
(34, 'PHYSICAL_HIT_MODIFIER', -21),
(35, 'MAGICAL_HIT_MODIFIER', -22),
(35, 'RANGE_HIT_MODIFIER', -22),
(35, 'PHYSICAL_HIT_MODIFIER', -22),
(36, 'MAGICAL_HIT_MODIFIER', -23),
(36, 'RANGE_HIT_MODIFIER', -23),
(36, 'PHYSICAL_HIT_MODIFIER', -23),
(37, 'MAGICAL_HIT_MODIFIER', -24),
(37, 'RANGE_HIT_MODIFIER', -24),
(37, 'PHYSICAL_HIT_MODIFIER', -24),
(38, 'MAGICAL_HIT_MODIFIER', -25),
(38, 'RANGE_HIT_MODIFIER', -25),
(38, 'PHYSICAL_HIT_MODIFIER', -25),
(39, 'MAGICAL_HIT_MODIFIER', -26),
(39, 'RANGE_HIT_MODIFIER', -26),
(39, 'PHYSICAL_HIT_MODIFIER', -26),
(40, 'MAGICAL_HIT_MODIFIER', -27),
(40, 'RANGE_HIT_MODIFIER', -27),
(40, 'PHYSICAL_HIT_MODIFIER', -27),
(41, 'MAGICAL_HIT_MODIFIER', -28),
(41, 'RANGE_HIT_MODIFIER', -28),
(41, 'PHYSICAL_HIT_MODIFIER', -28),
(42, 'MAGICAL_HIT_MODIFIER', -29),
(42, 'RANGE_HIT_MODIFIER', -29),
(42, 'PHYSICAL_HIT_MODIFIER', -29);


insert into skill_custom_effect (skill_basic_id, description, value) values
(43, 'Wzmacnia krytyczne uderzenie o', 14),
(44, 'Wzmacnia krytyczne uderzenie o', 15),
(45, 'Wzmacnia krytyczne uderzenie o', 17),
(46, 'Wzmacnia krytyczne uderzenie o', 18),
(47, 'Wzmacnia krytyczne uderzenie o', 20),
(48, 'Wzmacnia krytyczne uderzenie o', 21),
(49, 'Wzmacnia krytyczne uderzenie o', 23),
(50, 'Wzmacnia krytyczne uderzenie o', 24),
(51, 'Wzmacnia krytyczne uderzenie o', 26),
(52, 'Wzmacnia krytyczne uderzenie o', 27),
(53, 'Wzmacnia krytyczne uderzenie o', 29),
(54, 'Wzmacnia krytyczne uderzenie o', 30),
(55, 'Wzmacnia krytyczne uderzenie o', 32),
(56, 'Wzmacnia krytyczne uderzenie o', 33),
(57, 'Wzmacnia krytyczne uderzenie o', 35),
(58, 'Wzmacnia krytyczne uderzenie o', 36),
(59, 'Wzmacnia krytyczne uderzenie o', 38),
(60, 'Wzmacnia krytyczne uderzenie o', 39),
(61, 'Wzmacnia krytyczne uderzenie o', 41),
(62, 'Wzmacnia krytyczne uderzenie o', 42),
(63, 'Wzmacnia krytyczne uderzenie o', 44);